### ISSUE TITLE
Not supporting header containing plain language-country only, e.g., `en-US`

### ISSUE THREAD

**Issue by frankthelen** [opentable/accept-language-parser#24]
Hi,

if you switch language on an iPad (via Settings / General / Language & Region / iPad Language), Safari might *not* send the usual language-country + language combination (e.g., `en-US,en`) but a plain language-country only (e.g., `en-US`) without language fallback. Unfortunately, this is not supported by the accept language parser.

Expected behavior:
```
var parser = require("accept-language-parser"); // version 1.4.1
var language = parser.pick(['en', 'fr'], 'en-US'); // 'en'
```
Actual behavior:
```
var parser = require("accept-language-parser"); // version 1.4.1
var language = parser.pick(['en', 'fr'], 'en-US'); // null
```

Not sure if this should be supported.
Thank you.

**Comment by matteofigus** [comment]
@frankthelen I think the first argument of the `pick` is supposed to be a full language and you are providing the abbreviated format.

```js
var language = parser.pick(['en-US', 'fr-FR'], 'en-US') // en-US
var language2 = parser.pick(['en-US', 'fr-FR'], 'en') // en-US
```

**Comment by matteofigus** [comment]
Closing because of lack of interest. Please reopen if needed.

**Comment by frankthelen** [comment]
Well, strictly speaking, `en` is not an abbreviation. It means English but not country or region-specific. So, if I request 'en-US' but there is only `en` available, it should give me `en` as a reasonable default even if it's not the US variant of the language.

But anyway, as far as I know, it affects only iPads that are (sometimes?) not sending correct full `accept-language` headers. They are sending "en-US" instead of correctly "de-DE,de;..." in some cases. Haven't seen this behavior in any other browser/device.

**Comment by matteofigus** [comment]
@ArnoldZokas what's your opinion on that?

**Comment by sheerun** [comment]
In my use case I need to pick one of non-prefixed languages given prefixed accept-language. There should be at least an option to have this behavior :)
